horasNormales=168
pagoxHoras=(1000000/horasNormales)
horasExtras=20
pagoxHoraExtra=(pagoxHoras*0.25)
print(f"Nombre Trabajador: Luis Alfonso Montoya Ortega.")
print(f"Horas normales trabajadas:{horasNormales}")
print(f"Con un pago x hora de:{pagoxHoras}.")
print(f"Numero de horas extras: {horasExtras}.")
hijos=int(input("cuantos hijos tiene: "))
sueldoTotal=((pagoxHoras*horasNormales)+(pagoxHoraExtra*horasExtras))
deduccciones=(sueldoTotal*0.14)
print(f"Este es el total de deducciones: {deduccciones}.")
asignaciones=(250000+(173000*hijos)+180000)
print(f"El total de asignaciones es: {asignaciones}.")
sueldoNeto=(sueldoTotal-deduccciones+asignaciones)
print(f"El sueldo neto para el mes de diciembre seria: {sueldoNeto}.")